# Generated by Django 3.2.4 on 2021-10-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
