# Generated by Django 3.2.4 on 2021-10-28 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsequestion',
            name='form',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='form.form'),
            preserve_default=False,
        ),
    ]
