# Generated by Django 3.2.4 on 2021-11-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20211028_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='user_id',
        ),
    ]
