# Generated by Django 3.2.4 on 2021-11-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20211107_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='uname',
            field=models.UUIDField(),
        ),
    ]
