# Generated by Django 3.2.4 on 2021-11-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_alter_response_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='uname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
